site_name: Bumjoon Kang's Teaching Site
site_url: https://laus.snu.ac.kr/teaching-site/

theme:
  name: material
  language: ko

extra_css:
  - stylesheets/extra.css
  
nav:
  - Home: index.md
  - 도시와 주거:
      - 강의계획서: urbanism-housing/index.md
      - 2025-2: https://bumjoon.notion.site/Urbanism-and-Housing-d3e85f0ebcb14ecc9d211120ba308433?pvs=4          
