site_name: Bumjoon Kang's Courses
site_url: https://laus.snu.ac.kr/courses/

theme:
  name: material
  language: ko

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://laus.snu.ac.kr
  
nav:
  - LAUS Home: https://laus.snu.ac.kr
  - Courses: https://laus.snu.ac.kr/teaching
  - 도시와 주거:
      - 강의계획서: urbanism-housing/index.md
      - 주차별계획: urbanism-housing/schedule.md
      - Archive:
        - 2025-2: https://bumjoon.notion.site/Urbanism-and-Housing-d3e85f0ebcb14ecc9d211120ba308433?pvs=4          
